python = ">=3.9,<4.0"
numpy = "*"
torch = ">=2.1.0"
torchvision = ">=0.16.0"
tqdm = ">=4.66.2"
Pillow = ">=10.2.0"
supervision = ">=0.19.0"
gradio = ">=4.21.0"
chardet = ">=5.2.0"
ultralytics-yolov5 = ">=0.1.1"
ultralytics = ">=8.2.50"

