from setuptools import setup, find_packages

setup(
    name="PivotalWildlife",
    version="0.0.1",
    packages=find_packages(),
    url="https://github.com/PivotalFuture/CameraTraps.git",
    license="MIT",
    author="Jack Edney",
    author_email="jack.edney@pivotal.earth",
    description="a PyTorch Collaborative Deep Learning Framework for Conservation with a Pivotal twist",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    install_requires=[
        "numpy",
        "torch==2.1.0",
        "torchvision==0.16.0",
        "tqdm==4.66.2",
        "Pillow==10.2.0",
        "supervision==0.19.0",
        "gradio==4.21.0",
        "ultralytics-yolov5==0.1.1",
        "chardet==5.2.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    keywords="pytorch, wildlife, megadetector, conservation, animal, detection, classification",
    python_requires=">=3.9",
)
